// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_dev_boost_auth.Entities;

namespace api_dev_boost_auth.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20200830175951_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "96a1834b-5907-4a02-915c-c7c030f5834f",
                            ConcurrencyStamp = "51622cda-b7e5-4a80-b358-a6c4250f106b",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "4ce20842-6b7a-4aad-b477-7d793c9dcdc4",
                            ConcurrencyStamp = "964aec30-e986-46b9-8e54-3e57bd3ebdb5",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("api_dev_boost_auth.Entities.Models.ApontamentoHoras", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ApontamentoHorasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("HorasTrabalhadas")
                        .HasColumnType("float");

                    b.Property<string>("IdentificadorFuncionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ApontamentoHoras");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            HorasTrabalhadas = 50.0,
                            IdentificadorFuncionario = "Funcionario 1",
                            Mes = 4
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            HorasTrabalhadas = 168.0,
                            IdentificadorFuncionario = "Funcionario 1",
                            Mes = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
